CREATE TABLE IF NOT EXISTS docs (id TEXT PRIMARY KEY, body TEXT, rev INTEGER NOT NULL DEFAULT 0, created INTEGER NOT NULL, updated INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS limits (key TEXT NOT NULL, hour INTEGER NOT NULL, n INTEGER NOT NULL, PRIMARY KEY (key, hour));
CREATE TABLE IF NOT EXISTS inbox (id TEXT PRIMARY KEY, acct TEXT NOT NULL, dest TEXT NOT NULL, at INTEGER NOT NULL, kind TEXT NOT NULL, body TEXT NOT NULL, src TEXT NOT NULL DEFAULT '');
CREATE INDEX IF NOT EXISTS inbox_acct ON inbox (acct);
