// Joins sync.js and worker/sync/server.js into one file, worker/sync/dist/worker.js, which can be pasted
// into the Cloudflare dashboard or deployed with wrangler. Run `npm run build:worker` after changing either.
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');

function build() {
  const read = (f) => fs.readFileSync(path.join(root, f), 'utf8');
  return '// Generated by tools/build-worker.js from sync.js and worker/sync/server.js. Do not edit by hand.\n' +
    read('sync.js') + '\n' + read('worker/sync/server.js') + '\nexport default globalThis.SyncServer.worker;\n';
}
module.exports = { build };

if (require.main === module) {
  const out = path.join(root, 'worker/sync/dist/worker.js');
  fs.mkdirSync(path.dirname(out), { recursive: true });
  fs.writeFileSync(out, build());
  console.log('Wrote ' + path.relative(root, out));
}
